# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitcury < Formula
  desc "AI-Powered Git Automation CLI tool"
  homepage "https://github.com/lakshyajain-0291/gitcury"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lakshyajain-0291/gitcury/releases/download/v1.4.0/gitcury_1.4.0_darwin_amd64.tar.gz"
      sha256 "33ae25c4a64eb63805dc3e29aecf4a9735e2ef7293b89c03cff488431a4fd333"

      def install
        bin.install "gitcury"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lakshyajain-0291/gitcury/releases/download/v1.4.0/gitcury_1.4.0_darwin_arm64.tar.gz"
      sha256 "349d464f3eff55783278a0a65197d2b0007d8c582e8746b9bf8d3b51f69ec8aa"

      def install
        bin.install "gitcury"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/lakshyajain-0291/gitcury/releases/download/v1.4.0/gitcury_1.4.0_linux_amd64.tar.gz"
      sha256 "751d8d6ac13c8cf3a062d21ebc76ceda095d071b9cd5fe693a5330fd29fe96e5"
      def install
        bin.install "gitcury"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/lakshyajain-0291/gitcury/releases/download/v1.4.0/gitcury_1.4.0_linux_arm64.tar.gz"
      sha256 "50a4965eaeffd687708a0e67935d7ecdbc37f29942cc5376aa98e3d3ea4a120d"
      def install
        bin.install "gitcury"
      end
    end
  end

  test do
    system "#{bin}/gitcury --version"
  end
end
